# Generated by Django 5.2.8 on 2025-11-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdrf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='John', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Doe', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(help_text='Michael', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BinaryField(),
        ),
    ]
