# Generated by Django 5.2.8 on 2025-12-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdrf', '0003_permission_remove_user_is_admin_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
